config-version: 2
language: en_US
selection:
  tool: GOLD_AXE
messages:
  # Optional region transition messages.
  region-enter-enabled: false
  region-leave-enabled: false
  enter: '&aEntering region: &f%region%'
  leave: '&7Leaving region: &f%region%'
gui:
  event-icon: PAPER
editor:
  input-timeout-seconds: 120
